fix TypeScript error TS4023 "using name 'SchemaObjectInstance'"
error TS4023: Exported variable 'MyVariableName' has or is using name 'SchemaObjectInstance' from external module 'schema-object' but cannot be named.

This is because the interface is not exported from the module and is not globally accessible